
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: vuetify-app
spec:
  source:
    git:
      uri: https://github.com/miweinho/my-project.git
      ref: main
    type: Git
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile.openshift
  output:
    to:
      kind: ImageStreamTag
      name: vuetify-app:latest